### ISSUE TITLE
Clarifying Latest Update

### ISSUE THREAD

**Issue by SirNate0** [AeolusUX/R36S-DTB#1]
Hello, can you clarify what the latest update did? Why was the file renamed to r35s instead of r36s. Why does the dtb now now specify a `logo.gif` (and `logo_kernel.gif`) instead of a `logo{,_kernel}.bmp`. Why was `opp-1512000000` removed from the `cpu0-opp-table`? Why did the display timings change?

Overall, can you clarify whether I should use the old r36s dtb file with an R36S, or should I use the new r36s file?

**Comment by AeolusUX** [comment]
Both should work the same if you're not on an R35S. Files are changed because older batch of the R35S doesn't support the display timings of newer batches. The logo change I would have to confirm but I'm pretty sure I that wasn't replaced, I have tried gif before and it doesn't work for the device. Anyway that should still fall back to the 351mp dtb if it doesn't find any .gif so it doesn't matter. For opp-1512000000 according to christian from arkos it's a placebo and does nothing positive especially for 351 devices. It was added in the past and actually caused stability issues and in many cases slowed down emulation. This is why he reverted the overclock in later releases. This new dtb files came from the source code btw (Old one is decompiled from old dtb for R35S) and will be included on the next ArkOS update.
